Модуль 11
htmlacademy-javascript/270653-keksobooking-23 pull request #10
Opened 2021-07-02 10:51 UTC by MikhailinNik

2021-07-02 11:38 UTC, AlexMasterov requested changes

2021-07-02 11:38 UTC, AlexMasterov commented on js/message.js
> +const EventToString = {
<details>
<summary>message.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3b97e282a3f0f29230cb711318be576585b542c8/js/message.js#L3-L6
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3b97e282a3f0f29230cb711318be576585b542c8/js/message.js#L23-L24
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3b97e282a3f0f29230cb711318be576585b542c8/js/message.js#L32-L34
</details>

`EventToString`

Называется как _словарь_, а используется как _перечисление_.

Б8

Нужно использовать условный формат _перечисления_.

2021-07-02 11:38 UTC, AlexMasterov commented on js/message.js
> +const onItem = (item1, item2, event) => {
`event`

Б22

2021-07-02 11:38 UTC, AlexMasterov commented on js/message.js
> +const onItem = (item1, item2, event) => {
<details>
<summary>message.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3b97e282a3f0f29230cb711318be576585b542c8/js/message.js#L12-L16
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3b97e282a3f0f29230cb711318be576585b542c8/js/message.js#L23-L24
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3b97e282a3f0f29230cb711318be576585b542c8/js/message.js#L32-L34
</details>

`onItem`

Называется как коллбэк, но использует как простая функция.

Б6

Нужно записать название в формате простой функции.

2021-07-02 11:38 UTC, AlexMasterov commented on js/card.js
> +  // }
`//`

Б12

Нужно удалить.

2021-07-02 11:38 UTC, AlexMasterov commented on js/message.js
> +    isEscEvent ? item2.classList.add('hidden') : item2.classList.add('hidden');
`isEscEvent` — это _функция_, которая ничего не возвращает.

`isEscEvent` ? `item2.classList.add('hidden')` : `item2.classList.add('hidden')`

Приведение функции (без вызова) к булевому значению всегда возвращает `true`. Таким образом ветка с `else` (= `:`) недостижима. При этом обе ветки делают одно и тоже.

Б14

2021-07-02 11:38 UTC, AlexMasterov commented on js/map.js
> +
Сейчас после успешной отправки формы на сервер страница не переходит в состояние очистки.

См. ТЗ 2.5.

Нужно доработать.

2021-07-02 11:38 UTC, AlexMasterov commented on js/map.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/124268447-2fba6000-db42-11eb-9a76-047b3e1eabe4.png)
![image](https://user-images.githubusercontent.com/700213/124268581-5f696800-db42-11eb-8c86-65d543e5d964.png)

</details>

Сейчас после успешной отправки формы на сервер накапливаются элементы сообщения и обработчики на `document` с `keydown`, что ведет к утечке памяти.

Б26

2021-07-02 11:38 UTC, AlexMasterov commented on js/map.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/124268914-dacb1980-db42-11eb-9454-90bbc32dfdc7.png)

</details>

Появилась проблема с отображением фото. Нужно исправить.

2021-07-02 11:49 UTC, AlexMasterov requested changes

2021-07-02 11:49 UTC, AlexMasterov commented on js/map.js
> +
Сейчас сообщение успешной/неуспешной отправки можно закрыть нажатием на любую клавишу.

См. ТЗ 2.6, 2.7.

Нужно исправить.

2021-07-02 11:56 UTC, MikhailinNik commented on js/message.js
> +const onItem = (item1, item2, event) => {
вместо onItem, название функции setListenerEvent подходит?

2021-07-02 11:58 UTC, MikhailinNik commented on js/message.js
> +const EventToString = {
EventString подходит или лучше как то по другому назвать?

2021-07-02 11:58 UTC, AlexMasterov commented on js/message.js
> +const onItem = (item1, item2, event) => {
> вместо onItem, название функции setListenerEvent подходит?

Да, но сама функция ничего не делает.

2021-07-02 12:01 UTC, AlexMasterov commented on js/message.js
> +const EventToString = {
> EventString подходит или лучше как то по другому назвать?

Неудачное название, но для критерия достаточно. 

В описание критерия есть пример перечисления. Нужно также ключи объекта записать в верхнем регистре.

2021-07-03 13:02 UTC, AlexMasterov requested changes
К сожалению, нужно еще немного доработать.

2021-07-03 13:02 UTC, AlexMasterov commented on js/card.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/124355002-a8d7b700-dc17-11eb-9278-38db650159dd.png)

</details>

У карточек перестало правильно отображаться удобства: при наличии и в отсутствие данных показываются все удобств.

Б1

Это "сломалось" и нужно исправить.

2021-07-03 13:09 UTC, AlexMasterov requested changes

2021-07-03 13:09 UTC, AlexMasterov commented on js/message.js
> +  if (messageSucces.classList.contains('hidden')) {
message`Succes`

Опечатка.

[`Б 4`](https://up.htmlacademy.ru/javascript/23/criteries#b4)
> В качестве имён переменных и свойств используются **английские существительные**

Нужно исправить во всех местах.

2021-07-03 13:10 UTC, AlexMasterov requested changes

2021-07-03 13:10 UTC, AlexMasterov commented on js/message.js
> +const messageSucces = success.cloneNode(true);
message`Succes`

Опечатка.

[`Б 4`](https://up.htmlacademy.ru/javascript/23/criteries#b4)
> В качестве имён переменных и свойств используются **английские существительные**

Нужно исправить во всех местах.

2021-07-03 15:30 UTC, MikhailinNik commented on js/message.js
> +    messageError.remove();
Потому что при повторной отправке формы, сообщение об успешной/неуспешной отправки формы не показывается, потому что в DOM добавляется элемент div с классами 'success'/'error' и 'hidden'. Сообщение не показывается таким образом

2021-07-04 12:40 UTC, AlexMasterov approved these changes
Пож, замечание в остатке доработай при выполнении следующего задания.

2021-07-04 12:40 UTC, AlexMasterov commented on js/message.js
> +const onMessageKeydown = (evt) => {
Сейчас сообщение можно закрыть нажатием любой клавиши, а требуется только по `Esc`.

См. ТЗ 2.6, 2.7:
> Сообщение должно исчезать по нажатию на клавишу `Esc`

Нужно доработать.

2021-07-04 12:40 UTC, merged

2021-07-05 01:07 UTC, AlexMasterov commented on js/page.js
См. ТЗ 4.2:
> **Поле адреса должно быть заполнено всегда**, в том числе сразу после активации страницы

<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/9ba1083c16b2aaa31e26a588cb663ac7efc6c0d9/js/map.js#L99-L102
</details>

Если из обработчика `load` убрать вызов `renderInputAddress(specialMarker)`, то окажется, что в неактивном состояние страницы (которого нет) поле адреса будет пустым, что не соответствует ТЗ.

Нужно доработать.

2021-07-05 01:07 UTC, AlexMasterov commented on js/page.js
<details>
<summary>page.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/9ba1083c16b2aaa31e26a588cb663ac7efc6c0d9/js/page.js#L3
</details>

<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/9ba1083c16b2aaa31e26a588cb663ac7efc6c0d9/js/map.js#L2
</details>

`page.js` <-> `map.js`

Модули `page.js` и `map.js` напрямую вызывают методы друг друга и таким образом _непосредственно_ зависят друг от друга; _взаимозависимые_ модули не являются полностью отдельными модулями, будучи по сути частями одного большего модуля, что создает опасную ситуацию [циклической зависимости](https://en.wikipedia.org/wiki/Circular_dependency):

> In software design, **circular dependencies** between larger software modules are considered an **anti-pattern** because of their negative effects