Module12 task2
htmlacademy-javascript/270653-keksobooking-23 pull request #12
Opened 2021-07-11 16:55 UTC by MikhailinNik

2021-07-13 05:58 UTC, AlexMasterov requested changes

2021-07-13 05:58 UTC, AlexMasterov commented on js/api.js
>    post: 'https://23.javascript.pages.academy/keksobooking',
Б8

Нужно исправить:
```js
const RequestUrl = {
  GET: 'https://23.javascript.pages.academy/keksobooking/data',
  POST: 'https://23.javascript.pages.academy/keksobooking',
};
```

2021-07-13 05:58 UTC, AlexMasterov commented on js/avatar.js
> +const createItem = (item) => {
<details>
<summary>createItem</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/d800a668441de9ffbb13f99fec78fb70d1b2cec6/js/avatar.js#L12-L13
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/d800a668441de9ffbb13f99fec78fb70d1b2cec6/js/avatar.js#L15-L16
</details>

Б7

Могут придраться. 

Для числовых значений размера можно создать _перечисление_.

2021-07-13 05:58 UTC, AlexMasterov commented on js/avatar.js
> +const removeItem = (item) => item.innerHTML = '';
`=>` item.innerHTML `=` ''

Д27

2021-07-13 05:58 UTC, AlexMasterov commented on js/avatar.js
> +  return item.appendChild(image);
Желательно возвращать созданный элемент, а добавлять в другом месте.

2021-07-13 05:58 UTC, AlexMasterov commented on js/avatar.js
> +    const matches = FILE_TYPES.some((it) => fileName.endsWith(it));
FILE_TYPES.some((`it`) => fileName.endsWith(`it`));

Сокращение.

Б4

2021-07-13 05:58 UTC, AlexMasterov commented on js/message.js
<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/d800a668441de9ffbb13f99fec78fb70d1b2cec6/js/form.js#L29-L32
</details>
<details>
<summary>message.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/d800a668441de9ffbb13f99fec78fb70d1b2cec6/js/message.js#L66-L69
</details>

Д14

2021-07-13 05:58 UTC, AlexMasterov commented on js/message.js
>  const EscapeKey = {
```js
const KeyboardKey = {
  ESCAPE: 'Escape',
  ESC: 'Esc',
};
```

2021-07-13 05:58 UTC, AlexMasterov commented on js/message.js
`data.js`
`random.js`

Нужно удалить.

Б12

2021-07-13 05:58 UTC, AlexMasterov commented on js/form.js
>  import { formFilters } from './filter.js';
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/d800a668441de9ffbb13f99fec78fb70d1b2cec6/js/filter.js#L33
</details>

`any`

Б7

Могут придраться.

2021-07-13 05:58 UTC, AlexMasterov commented on js/form.js
<details>
<summary>page.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/d800a668441de9ffbb13f99fec78fb70d1b2cec6/js/page.js#L15
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/d800a668441de9ffbb13f99fec78fb70d1b2cec6/js/page.js#L19
</details>

`10`

Б7

2021-07-14 13:36 UTC, MikhailinNik commented on js/avatar.js
> +const removeItem = (item) => item.innerHTML = '';
Не совсем понимаю, как реализовать это по другому, подскажи пожалуйста

2021-07-14 13:43 UTC, AlexMasterov commented on js/avatar.js
> +const removeItem = (item) => item.innerHTML = '';
> Не совсем понимаю, как реализовать это по другому, подскажи пожалуйста

```js
const clearElement = (element) => {
  element.innerHTML = '';
}
```

2021-07-14 13:49 UTC, MikhailinNik commented on js/avatar.js
> +const removeItem = (item) => item.innerHTML = '';
Так просто, значит я не так понял изначально...
Благодарю!

2021-07-14 16:26 UTC, AlexMasterov requested changes

2021-07-14 16:26 UTC, AlexMasterov commented on js/form.js
<details>
<summary>util.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/f01fe4342e44b61940dbe4b1ed931ee10dd1053a/js/util.js#L48
</details>

Б10

2021-07-14 16:26 UTC, AlexMasterov commented on js/form.js
<details>
<summary>message.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/f01fe4342e44b61940dbe4b1ed931ee10dd1053a/js/message.js#L1
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/f01fe4342e44b61940dbe4b1ed931ee10dd1053a/js/message.js#L3
</details>

`//`

Б12

2021-07-14 16:26 UTC, AlexMasterov commented on js/form.js
<details>
<summary>message.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/f01fe4342e44b61940dbe4b1ed931ee10dd1053a/js/message.js#L41
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/f01fe4342e44b61940dbe4b1ed931ee10dd1053a/js/message.js#L46
</details>

`function`

Д5

2021-07-14 16:26 UTC, AlexMasterov commented on js/form.js
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/f01fe4342e44b61940dbe4b1ed931ee10dd1053a/js/map.js#L8-L12
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/f01fe4342e44b61940dbe4b1ed931ee10dd1053a/js/map.js#L14-L18
</details>

Б8

На всякий случай запиши эти объекты в формате _перечисления_.

2021-07-14 16:26 UTC, AlexMasterov commented on js/form.js
Если применить фильтры и нажать на кнопку "Очистить", то выбор фильтрации сбрасывается, но метки не появляются, т.е. фильтрация не сбрасывается.

См. ТЗ:
> фильтрация (состояние фильтров и отфильтрованные метки) сбрасывается

Нужно разобраться и исправить.

2021-07-14 16:26 UTC, AlexMasterov commented on js/form.js
Если открыть карточку (баллун) и нажать на кнопку "Очистить", то карточка остается открытой.

Желательно закрывать карточку.

2021-07-14 19:13 UTC, AlexMasterov approved these changes

2021-07-14 19:13 UTC, AlexMasterov commented on js/form.js
> +  });
См. 5.1: 
> Полный список похожих объявлений загружается после перехода страницы в активное состояние с сервера

Сейчас данные с сервера загружаются после отправки или сброса страницы, что формально не соответствует ТЗ.

2021-07-14 19:13 UTC, AlexMasterov commented on js/map.js
См. формат _перечисления_ в критерии Б8:

```js
// Перечисление
const StatusCode = {
  OK: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
};
```
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/15bfae4091cb4b6a18a4cf0d15cef88e698da265/js/map.js#L8
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/15bfae4091cb4b6a18a4cf0d15cef88e698da265/js/map.js#L14
</details>

Нужно в обоих случаях исправить название.

2021-07-14 19:13 UTC, merged