Выполнил задание №8
htmlacademy-javascript/270653-keksobooking-23 pull request #3
Opened 2021-06-06 17:07 UTC by MikhailinNik

2021-06-07 09:27 UTC, AlexMasterov requested changes

2021-06-07 09:27 UTC, AlexMasterov commented on js/main.js
> +    location: createLocation()}
```js
const advert1 = similarObject[0];

typeof advert1.location.lat // string
typeof advert1.location.lng // string
```


См. задание:
> `location`, объект — местоположение в виде географических координат. Состоит из двух полей:

> `lat`, **число с плавающей точкой** — широта, случайное значение от 35.65000 до 35.70000.

> `lng`, **число с плавающей точкой** — долгота, случайное значение от 139.70000 до 139.80000

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/64ac180c546ae663f23d02c10e659c6d72492f7a/js/main.js#L85-L86
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/64ac180c546ae663f23d02c10e659c6d72492f7a/js/main.js#L15-L24
</details>

Сейчас функция `getRandomNumberFloat` вместо _числа_ возвращает _строку_.

Нужно исправить.

2021-06-07 09:27 UTC, AlexMasterov commented on js/main.js
> +const createOffer = () =>
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/64ac180c546ae663f23d02c10e659c6d72492f7a/js/main.js#L78
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/64ac180c546ae663f23d02c10e659c6d72492f7a/js/main.js#L80
</details>

👍🏻

2021-06-08 19:08 UTC, MikhailinNik commented on js/main.js
> +
Сделал сначала так: 
```
const DESCRIPTIONS = [
  'кухня',
  'ванная',
  'гостинная',
  'туалет',
  'спальня'
];
```
и ESLint пишет ошибку  _Missing trailing comma  comma-dangle_

2021-06-08 19:11 UTC, AlexMasterov commented on js/main.js
> +
> и ESLint пишет ошибку _Missing trailing comma comma-dangle_

Нужно добавить "висячую запятую":
```js
const DESCRIPTIONS = [
  'кухня',
  'ванная',
  'гостинная',
  'туалет',
  'спальня', // <-
];
```

2021-06-09 19:11 UTC, MikhailinNik commented on js/main.js
> +    author: createAuthor(),
Саш, я исправил практически всё, кроме этого, у меня не получается сгенерировать массив так, чтобы элемент не повторялся. Подскажи пожалуйста, как это можно лучше сделать?

2021-06-09 19:21 UTC, AlexMasterov commented on js/main.js
> +    author: createAuthor(),
> Саш, я исправил практически всё, кроме этого, у меня не получается сгенерировать массив так, чтобы элемент не повторялся. Подскажи пожалуйста, как это можно лучше сделать?

Как вариант, генерировать уникальный идентификатор (`id`) вне функции.

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3835a47623bb21291a8c5ab44d833e61f59eb86b/js/main.js#L120
</details>

В случае с массивом можно использовать его (числовой) индекс:
```diff
- const similarObjects = new Array(10).fill(null).map(() => createObject());
+ const similarObjects = new Array(10).fill(null).map((_, idx) => createObject(idx + 1));
```

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/3835a47623bb21291a8c5ab44d833e61f59eb86b/js/main.js#L114-L115
</details>

```diff
-  const createObject = () => ({
+  const createObject = (id) => ({
```
```diff
- author: createAuthor(),
+ author: { avatar: `img/avatars/user${id}.png`}
```
Осталось добавить условие для `id`, чтобы подставлять ведущий `0`.

2021-06-09 19:21 UTC, AlexMasterov commented on js/main.js
> +const createObject = () => ({
Подсказывал в других замечаниях:
```diff
- const createObject = () => ({
+ const createAdvert = () => ({
```

2021-06-09 19:25 UTC, AlexMasterov requested changes

2021-06-09 19:25 UTC, AlexMasterov commented on js/main.js
> +  const arr = [];
`arr`

Б4, Б5

2021-06-10 08:19 UTC, AlexMasterov requested changes
К сожалению, нужно еще немного доработать.

2021-06-10 08:19 UTC, AlexMasterov commented on js/main.js
> +    location: createLocation(),
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/906fdfa9bf8157b3d16fa60450f365f02d73d40d/js/main.js#L90-L94
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/906fdfa9bf8157b3d16fa60450f365f02d73d40d/js/main.js#L97-L101
</details>

Из-за одного значения по условию не стоит полностью дублировать функцию.

[`Д 14`](https://up.htmlacademy.ru/javascript/23/criteries#d14)
> Отсутствует дублирование кода

2021-06-10 08:19 UTC, AlexMasterov commented on js/main.js
> +      author: { avatar: `img/avatars/user${0}${id}.png`},
author: { avatar: `img/avatars/user`${0}`${id}.png`},

Здесь `0` — это не _выражение_ и его можно сразу записать строкой.

2021-06-10 08:19 UTC, AlexMasterov commented on js/main.js
> +const createLocation = () => ({
```
(10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {lat: 35.66906, lng: 139.7745}
1: {lat: 35.66906, lng: 139.7745}
2: {lat: 35.66906, lng: 139.7745}
3: {lat: 35.66906, lng: 139.7745}
4: {lat: 35.66906, lng: 139.7745}
5: {lat: 35.66906, lng: 139.7745}
6: {lat: 35.66906, lng: 139.7745}
7: {lat: 35.66906, lng: 139.7745}
8: {lat: 35.66906, lng: 139.7745}
9: {lat: 35.66906, lng: 139.7745}
```
Сейчас у всех предложений одинаковый `location`.

См. задание:
> `location`, объект — местоположение в виде географических координат. Состоит из двух полей:

> `lat`, число с плавающей точкой — широта, **случайное значение** от 35.65000 до 35.70000.

> `lng`, число с плавающей точкой — долгота, **случайное значение** от 139.70000 до 139.80000

Нужно доработать.

> Это важно для тестирования, иначе все метки на карте будут рендериться в одной точке

2021-06-10 08:19 UTC, AlexMasterov commented on js/main.js
> +  types: getRandomArrayElements(TYPES),
`types`: getRandomArrayElements(TYPES),

Множ. число, хотя это не массив, а строка.

См. внимательно задание:
> `type`, **строка** — **одно** из пяти фиксированных значений: `palace`, `flat`, `house`, `bungalow` или `hotel`

Нужно исправить.

2021-06-10 08:19 UTC, AlexMasterov commented on js/main.js
> +const getRandomArrayElements = (items) => items[getRandomNumber(0, items.length - 1)];
const getRandomArray`Elements` = (`items`) => `items`[getRandomNumber(0, `items`.length - 1)];

> Нет единообразия

Возвращает _одно_ значение из массива:
```diff
- const getRandomArrayElements = (items) => items[getRandomNumber(0, items.length - 1)];
+ const getRandomArrayItem = (items) => items[getRandomNumber(0, items.length - 1)];
```

2021-06-10 08:19 UTC, AlexMasterov commented on js/main.js
> +const similarObjects = new Array(10).fill(null).map((value, idx) => createAdvert(idx + 1));
const `similarObjects` = new Array(10).fill(null).map((value, idx) => create`Advert`(idx + 1));

Снова `similar` и `Objects` 😟

Нужно исправить:

```diff
- const similarObjects = new Array(10).fill(null).map((value, idx) => createAdvert(idx + 1));
+ const adverts = Array.from({ length: 10 }, (value, idx) => createAdvert(idx + 1));
```

См. [Array.`from`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BE%D1%87%D0%BD%D0%BE%D0%B9_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8_%D0%B8_array.from()).

2021-06-10 11:45 UTC, MikhailinNik commented on js/main.js
> +const createLocation = () => ({
А здесь я так и не понял, как сгенерированное случайное число для lat и lng вставить в объект offer: {adress}

2021-06-10 11:45 UTC, MikhailinNik commented on js/main.js
> +    location: createLocation(),
здесь надо написать отедльную функцию для объекта author?

2021-06-10 11:59 UTC, AlexMasterov commented on js/main.js
> +const createLocation = () => ({
> А здесь я так и не понял, как сгенерированное случайное число для lat и lng вставить в объект offer: {adress}

Достаточно сгенерировать координаты (`location`) внутри функции `createAdvert`, сохранить результат в переменную и с её помощью _переиспользовать_ объект для `.location` и `.offer.address`.

2021-06-11 05:34 UTC, AlexMasterov commented
👍🏻

2021-06-11 05:34 UTC, merged