Генерации разметки похожих объявлений
htmlacademy-javascript/270653-keksobooking-23 pull request #5
Opened 2021-06-16 16:33 UTC by MikhailinNik

2021-06-16 18:14 UTC, AlexMasterov requested changes

2021-06-16 18:14 UTC, AlexMasterov commented on js/popup.js
> +popupFeatures.forEach((item, index) => {
```js
const advert1 = advert[0];
advert1.offer.features // ['parking', 'elevator']
```
```
NodeList(6) [
  li.popup__feature.popup__feature--wifi,
  li.popup__feature.popup__feature--dishwasher,
  li.popup__feature.popup__feature--parking,
  li.popup__feature.popup__feature--washer,
  li.popup__feature.popup__feature--elevator,
  li.popup__feature.popup__feature--conditioner,
]
```
![image](https://user-images.githubusercontent.com/700213/122269811-4d52bd00-cee6-11eb-96da-3f109a1a73a5.png)

В объявление выбрано два удобства: `parking` и `elevator`, но в его балуне отображаются все.

Нужно исправить.

2021-06-16 18:14 UTC, AlexMasterov commented on js/popup.js
> +mapCanvas.appendChild(fragment);
<details>
<summary>popup.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/96067cdf715542251eb322df36e3e7deda73bb73/js/popup.js#L16-L25
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/96067cdf715542251eb322df36e3e7deda73bb73/js/popup.js#L45-L48
</details>

Далее по заданию (и в итоге по ТЗ) потребуется создавать/открывать балун для любого объявления, но сейчас он создается _один_ раз на всё приложение и его нельзя переиспользовать.

Недоработка в этом задание будет стоить переработки в следующих.

2021-06-16 18:14 UTC, AlexMasterov commented on js/popup.js
> +
```
popup.js:19 Uncaught TypeError: Cannot read property 'title' of undefined
    at popup.js:19
```
Если у объекта объявления удалить `.offer` или его вложенные свойства, то в консоли появляются ошибки, а в разметке балуна `undefined`.

См. задание:
> Предусмотрите ситуацию, когда данных для заполнения не хватает. Например, отсутствует описание. **В этом случае соответствующий блок в карточке скрывается**

Нужно доработать.

2021-06-16 18:14 UTC, AlexMasterov commented on js/popup.js
> +const similarObject = {
<details>
<summary>popup.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/96067cdf715542251eb322df36e3e7deda73bb73/js/popup.js#L17-L24
</details>

**10x** `adverts[0]`

Получение одно и того же элемента из массива повторяется 10 раз.

2021-06-16 18:19 UTC, AlexMasterov requested changes

2021-06-16 18:19 UTC, AlexMasterov commented on js/popup.js
> +  type: popupType.textContent = adverts[0].offer.types,
![image](https://user-images.githubusercontent.com/700213/122271602-4036cd80-cee8-11eb-8397-cd26771636bb.png)

См. задание:
В блок `.popup__type` выведите тип жилья `offer.type`, **сопоставив с подписями**:
> **`Квартира` для `flat`**
> `Бунгало` для `bungalow`
> `Дом` для `house`
> `Дворец` для `palace`
> `Отель` для `hotel`

Нужно `offer.type` сопоставить с подписями: вместо `flat` должно отображаться `Квартира` и т.п.

2021-06-17 13:55 UTC, MikhailinNik commented on js/popup.js
> +  photos: popupPhotos.innerHTML = `<img src='${adverts[0].offer.photos}'>`,
Подскажи пожалуйста, в чем у меня проблема? 
`photo: popupPhotos.innerHTML = templatePhoto.setAttribute('src', item.offer.photos)`
`console.log(someAdvert[0].photo);`
возваращет undefinde, почему?

2021-06-17 14:52 UTC, MikhailinNik commented on js/popup.js
> +
Подскажи пожалуйста, как мне это реализовать? Я пытался по разному сделать, но так и не понял, что мне надо сделать и как, вот пример: ```
const condition = () => Object.values(someAdvert).map((value) => {
  if (someAdvert.includes(value === null)) {
    return console.log('aaaaaa');
  }
});
console.log(condition());
```

2021-06-17 18:03 UTC, AlexMasterov requested changes

2021-06-17 18:03 UTC, AlexMasterov commented on js/popup.js
> +const similarObject = {
<details>
<summary>popup.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/96067cdf715542251eb322df36e3e7deda73bb73/js/popup.js#L17-L24
</details>

title`:` popupTitle.textContent `=` adverts[0].offer.title,
_и т.п._

[`Д 27`](https://up.htmlacademy.ru/javascript/23/criteries#d27)
> Оператор присваивания не используется как часть выражения

2021-06-17 18:06 UTC, AlexMasterov commented on js/popup.js
> +  photos: popupPhotos.innerHTML = `<img src='${adverts[0].offer.photos}'>`,
Для начала, подобный код нарушает сразу три критерия:

templatePhoto.`setAttribute`('src', item.offer.photos)

Д7

popupPhotos.`innerHTML` = `templatePhoto.setAttribute('src', item.offer.photos)`

Д8

photo`:` popupPhotos.innerHTML `=` templatePhoto.setAttribute('src', item.offer.photos)

Д27

2021-06-17 18:08 UTC, AlexMasterov commented on js/popup.js
> +  photos: popupPhotos.innerHTML = `<img src='${adverts[0].offer.photos}'>`,
> Подскажи пожалуйста, в чем у меня проблема?
> `photo: popupPhotos.innerHTML = templatePhoto.setAttribute('src', item.offer.photos)`
> `console.log(someAdvert[0].photo);`
> возваращет undefinde, почему?

См. [Element.`setAttribute`](https://developer.mozilla.org/ru/docs/Web/API/Element/setAttribute) — метод не возвращает результата.

Кроме этого, ты снова пытаешься добавить весь массив (через неявное приведения его к строке) одному атрибуту `src`.

2021-06-17 18:19 UTC, AlexMasterov commented on js/popup.js
> +mapCanvas.appendChild(fragment);
> Не совсем понял, объясни пожалуйста, создавать/открывать балун?

См. [`ТЗ 5.4`](https://up.htmlacademy.ru/javascript/23/project/keksobooking#keksobooking-5-4):
> При нажатии на метку похожего объявления, показывается балун (предоставляется API карт) с подробной информацией об объявлении (далее — карточка)

Каким образом текущие решение поможет это реализовать?

Сейчас код создания и карточки выполняется в модуле _один_ раз и используется фиксированные тест. данные — подобный код нельзя переиспользовать в других модулях, используя разные данные с объявлениями. Таким образом подобное решение позволяет _формально_ выполнить задание, но никак не помогает в реализации ТЗ.

2021-06-17 18:29 UTC, AlexMasterov commented on js/popup.js
> +
> Подскажи пожалуйста, как мне это реализовать? Я пытался по разному сделать, но так и не понял, что мне надо сделать и как, вот пример: ```
> const condition = () => Object.values(someAdvert).map((value) => {
> if (someAdvert.includes(value === null)) {
> return console.log('aaaaaa');
> }
> });
> console.log(condition());

Почему опять `null`?
Обращение к свойству, которого нет, возвращает `undefined` (= нет _никакого_ значения).

Нужно проверить наличие каждого свойства в объекте и в его отсутствие скрыть/удалить соотвествующий блок в разметке карточки.

2021-06-17 18:38 UTC, AlexMasterov requested changes

2021-06-17 18:38 UTC, AlexMasterov commented on js/popup.js
> +const popupPhotos = popup.querySelector('.popup__description');
const `popupPhotos` = popup.querySelector(`'.popup__description'`);

См. задание:
> В блок `.popup__photos` выведите все фотографии из списка `offer.photos`

> **Каждая из строк массива `photos` должна записываться как атрибут `src` соответствующего изображения**

2021-06-17 18:42 UTC, AlexMasterov requested changes

2021-06-17 18:42 UTC, AlexMasterov commented on js/popup.js
> +const popupPhotos = popup.querySelector('.popup__description');
Сейчас не используется описание объявления `offer.description`.

См. задание:
> В блок `.popup__description` выведите описание объекта недвижимости `offer.description`

Нужно доработать.

2021-06-17 23:33 UTC, AlexMasterov requested changes

2021-06-17 23:33 UTC, AlexMasterov commented on js/popup.js
> +  capacity: popupTextCapacity.textContent = `${adverts[0].offer.rooms} комнаты для ${adverts[0].offer.guests}`,
`${adverts[0].offer.rooms} комнаты для ${adverts[0].offer.guests}`

См. задание:
> Выведите количество гостей и комнат `offer.rooms` и `offer.guests` в блок `.popup__text--capacity` строкой вида `{{offer.rooms}}` комнаты для `{{offer.guests}}` **гостей**. Например, «2 комнаты для 3 **гостей**»

Нужно дописать "гостей".

2021-06-18 08:40 UTC, AlexMasterov commented on js/popup.js
> +
> не понял, что мне надо сделать

<details>
<summary>data.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/96067cdf715542251eb322df36e3e7deda73bb73/js/data.js#L40-L50
</details>

В этом месте закомментируй любое свойство  и обработай его отсутствие при заполнение карточки. Если свойства нет, то блок (элемент) карточки нужно скрыть или удалить.

2021-06-20 15:11 UTC, AlexMasterov approved these changes
Пожалуйста, мелкие замечания в остатке доработай при выполнении следующего задания.

2021-06-20 15:11 UTC, AlexMasterov commented on js/card.js
> +  card.querySelector('.popup__text--time').textContent = offer.checkin || offer.checkout === undefined ? '' : `Заезд после ${offer.checkin}, выезд до ${offer.checkout}`;
```js
offer.checkin || offer.checkout === undefined
```

```js
const offer = { checkout: '15:00' };

card.querySelector('.popup__text--time').textContent // 'Заезд после undefined, выезд до 15:00'
```
Заезд после `undefined`, выезд до 15:00

Нужно доработать проверку.

2021-06-20 15:11 UTC, AlexMasterov commented on js/card.js
> +  card.querySelector('.popup__text--capacity').textContent = offer.rooms === undefined ? '' : `${offer.rooms} комнаты для ${offer.rooms} гостей`;
`${offer.`rooms`} комнаты для ${offer.`rooms`} гостей

Сейчас для кол. гостей используется значение из `offer.rooms`.

См. задание:
> Выведите количество гостей и комнат `offer.rooms` и `offer.guests` в блок `.popup__text--capacity` строкой вида {{offer.`rooms`}} комнаты для {{offer.`guests`}} гостей

Нужно исправить.

2021-06-20 15:11 UTC, AlexMasterov commented on js/main.js
> +import './card.js';
`import './card.js';`

Нужно удалить.

2021-06-20 15:11 UTC, AlexMasterov commented on js/map.js
> +const offerTypeEnToRu = {
Словарь (объект) нужно перенести в модуль `card.js`, где он непосредственно используется (или куда-нибудь в `util.js`, обернув в функцию).

> В случае переноса словаря в модуль `card.js` экспортировать от туда его не нужно

2021-06-20 15:11 UTC, merged