Модуль 9
htmlacademy-javascript/270653-keksobooking-23 pull request #9
Opened 2021-06-27 15:31 UTC by MikhailinNik

2021-06-27 16:14 UTC, AlexMasterov requested changes
Тревожно видеть, как сильно упростили задание и ТЗ 🤔

2021-06-27 16:14 UTC, AlexMasterov commented on js/map.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/123551338-fa94c300-d779-11eb-9652-af539ba97553.png)

</details>

Если балун в фокусе, то его закрытие по `Esc` не работает.

> По новому ТЗ это больше вообще не требуется

2021-06-27 16:14 UTC, AlexMasterov commented on js/map.js
См. ТЗ 4.1:
> Приблизительный адрес квартиры указывается _перемещением_ специальной метки по карте Токио. **Содержимое поля адреса должно всегда соответствовать координатам метки**

Сейчас _при перемещение_ главной метки координаты адреса не изменяются.

Нужно доработать.

2021-06-27 16:14 UTC, AlexMasterov commented on js/validation.js
<details>
<summary>validation.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/0ae15c203655e113637712b27866d5277b3a1a34/js/validation.js#L38
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/0ae15c203655e113637712b27866d5277b3a1a34/js/validation.js#L60
</details>

Желательно самостоятельно придумать более содержательное сообщение.

2021-06-27 16:14 UTC, AlexMasterov commented on js/map.js
> +const getMarkers = (objects) => {
На JS2 это будет нарушением критерия (и вообще):
```diff
- const getMarkers = (objects) => {
+ const getMarkers = (adverts) => {
```

2021-06-27 16:14 UTC, AlexMasterov commented on js/map.js
> +const createMarker = (object) => {
```diff
- const createMarker = (object) => {
+ const createMarker = (advert) => {
```

2021-06-27 16:24 UTC, AlexMasterov commented on js/map.js
> +  });
```js
 objects.forEach(createMarker);
```

2021-06-27 16:26 UTC, AlexMasterov requested changes

2021-06-27 16:26 UTC, AlexMasterov commented on js/map.js
> +getMarkers(adverts);
См. ТЗ 5.1:
> Полный список похожих объявлений загружается _после_ перехода страницы в активное состояние

Сейчас марки добавляют _до_ перехода страницы в активное состояние.

2021-06-27 17:47 UTC, MikhailinNik commented on js/map.js
> +getMarkers(adverts);
Эту функцию getMarkers можно передать в функцию activatePage(функция, которая переводит страницу в активное состояние)?

2021-06-27 17:51 UTC, AlexMasterov commented on js/map.js
> +getMarkers(adverts);
> Эту функцию getMarkers можно передать в функцию activatePage(функция, которая переводит страницу в активное состояние)?

Да, как вариант.

<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/0ae15c203655e113637712b27866d5277b3a1a34/js/map.js#L83
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/0ae15c203655e113637712b27866d5277b3a1a34/js/map.js#L28-L31
</details>

Важно понимать, что здесь эта функция выполняется _синхронно_ (сразу), а карта загружается по событию `load`, асинхронно (= отложено).

2021-06-27 17:55 UTC, MikhailinNik commented on js/map.js
> +const LNG_CENTR_TOKYO = 139.692;
```
const LAT_CENTRE_TOKYO = 35.6894;
const LNG_CENTRE_TOKYO = 139.692;
const URL_MAIN_ICON =  './img/main-pin.svg';
const SIZE_MAIN_ICON = [52, 52];
const ANCHOR_MAIN_ICON = [26, 52];
const URL_OTHER_ICON = '../img/pin.svg';
const SIZE_OTHER_ICON = [40, 40];
const ANCHOR_OTHER_ICON = [20, 40];
```
Как мне лучше назвать перечисление координат центра токио?(centreTokyoToCoordinates)?
перечисление основной иконки(MAIN_ICON)?

2021-06-27 17:59 UTC, MikhailinNik commented on js/map.js
Не совсем понял, у меня же координаты адреса основной метки изменяются при её перемещении

2021-06-27 18:02 UTC, AlexMasterov commented on js/map.js
> +const LNG_CENTR_TOKYO = 139.692;
> ```
> const LAT_CENTRE_TOKYO = 35.6894;
> const LNG_CENTRE_TOKYO = 139.692;
> const URL_MAIN_ICON =  './img/main-pin.svg';
> const SIZE_MAIN_ICON = [52, 52];
> const ANCHOR_MAIN_ICON = [26, 52];
> const URL_OTHER_ICON = '../img/pin.svg';
> const SIZE_OTHER_ICON = [40, 40];
> const ANCHOR_OTHER_ICON = [20, 40];
> ```
> 
> Как мне лучше назвать перечисление координат центра токио?(centreTokyoToCoordinates)?
> перечисление основной иконки(MAIN_ICON)?

Это выглядит немного несуразно, но может помочь формального замечания по критериям.

`const SIZE_MAIN_ICON = [52, 52];` и т.п.

Массивы нужно назвать во множ. числе.

`const URL_MAIN_ICON =  './img/main-pin.svg';`

Путь до картинок — это не [URL](https://ru.wikipedia.org/wiki/URL), а именно _путь_ (`path`). 

```js
const LAT_CENTRE_TOKYO = 35.6894;
const LNG_CENTRE_TOKYO = 139.692;
```
Во первых, `CENTER`.

Нужно вынести общею часть названия в название перечисления, например, так:

```js
const TokyoCenterCoord = {
  LAT: 35.6894,
  LNG: 139.692,
}
```

2021-06-27 18:04 UTC, AlexMasterov commented on js/map.js
> Не совсем понял, у меня же координаты адреса основной метки изменяются при её перемещении

Координаты изменяются после перемещения (`dragend`), а не при перемещение (`move`).

См. [полезный ответ авторов](https://up.htmlacademy.ru/javascript/23/module/9/questions#:~:text=%D0%AF%20%D0%B4%D0%B0%D0%BC%20%D0%B2%D0%B0%D0%BC%20%D1%83%D0%B4%D0%BE%D1%87%D0%BA%D1%83%2C%20%D0%B0%20%D0%BD%D0%B5%20%D1%80%D1%8B%D0%B1%D1%83%20%3A-)).

2021-06-27 21:45 UTC, AlexMasterov requested changes
Нужно еще немного доработать.

2021-06-27 21:45 UTC, AlexMasterov commented on js/map.js
> +
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/1f309823ead3a024c477735edb7b9a7c0b913a24/js/map.js#L9-L13
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/1f309823ead3a024c477735edb7b9a7c0b913a24/js/map.js#L15-L19
</details>

См. https://github.com/htmlacademy-javascript/270653-keksobooking-23/pull/9#discussion_r659340675

[`Б 7`](https://up.htmlacademy.ru/javascript/23/criteries#b7)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

Нужно название объектов записать в формате _обычной_ константы (но не формате _перечисления_).

> Всё это глупость во имя формализма

2021-06-27 21:45 UTC, AlexMasterov commented on js/map.js
> +  inputAddress.value = `${address.lat.toFixed(5)},${address.lng.toFixed(5)}`;
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/1f309823ead3a024c477735edb7b9a7c0b913a24/js/map.js#L45-L46
https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/1f309823ead3a024c477735edb7b9a7c0b913a24/js/map.js#L83-L84
</details>

[`Д 14`](https://up.htmlacademy.ru/javascript/23/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2021-06-27 21:45 UTC, AlexMasterov commented on js/map.js
> +  inputAddress.value = `${address.lat.toFixed(5)},${address.lng.toFixed(5)}`;
См. внимательно https://github.com/htmlacademy-javascript/270653-keksobooking-23/pull/9#discussion_r659340314

35.68268`,`139.67709

Не исправлено: после запятой `,` **нет пробела**.

См. ТЗ 4.3:
> Формат значения поля адреса: **`lat, lng`**, где `lat` и `lng` — это координаты метки

2021-06-27 21:45 UTC, AlexMasterov commented on js/page.js
> +  getMarkers(adverts);
`activateFilter();`
`getMarkers(adverts);`

Сейчас форма фильтрации активируется _до_ "загрузки" (и рендеринга) объявлений.

См. внимательно ТЗ 5.10:
> **Форма**, с помощью которой производится **фильтрация** похожих объявлений на момент открытия страницы заблокирована и **становится доступной только после окончания загрузки всех похожих объявлений**, которые в свою очередь начинают загружаться только после загрузки и успешной инициализации карты

Нужно исправить порядок в соответствие ТЗ.

2021-06-27 21:45 UTC, AlexMasterov commented on js/map.js
>  };
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/1f309823ead3a024c477735edb7b9a7c0b913a24/js/map.js#L76-L78
</details>

`get`Markers

Функция ничего не возвращает, но в название содержит глагол `get`.

[`Б 6`](https://up.htmlacademy.ru/javascript/23/criteries#b6)
> **Название функции должно** быть глаголом и **соответствовать действию**, которое выполняет функция. 

> Например, можно использовать глагол `get` для функций и методов, **которые что-то возвращают**

Нужно использовать другой глагол, который соответствует действию функции.

2021-06-28 14:47 UTC, MikhailinNik commented on js/map.js
> +  inputAddress.value = `${address.lat.toFixed(5)},${address.lng.toFixed(5)}`;
как лучше назвать функцию? getValue подойдет?

2021-06-28 15:03 UTC, MikhailinNik commented on js/map.js
>  };
Это же функция показывает похожие объявления, глагол show для этого подходит?

2021-06-28 17:30 UTC, AlexMasterov commented on js/map.js
>  };
> Это же функция показывает похожие объявления, глагол show для этого подходит?

Вполне.

2021-06-28 17:35 UTC, AlexMasterov commented on js/map.js
> +  inputAddress.value = `${address.lat.toFixed(5)},${address.lng.toFixed(5)}`;
> как лучше назвать функцию? getValue подойдет?

Слишком абстрактно.

См. также внимательно [похожие замечание](https://github.com/htmlacademy-javascript/270653-keksobooking-23/pull/9#discussion_r659380032):
[`Б 6`](https://up.htmlacademy.ru/javascript/23/criteries#b6)
> **Название функции должно** быть глаголом и **соответствовать действию**, которое выполняет функция. 

> Например, можно использовать глагол `get` для функций и методов, **которые что-то возвращают**

https://github.com/htmlacademy-javascript/270653-keksobooking-23/blob/1f309823ead3a024c477735edb7b9a7c0b913a24/js/map.js#L45-L46

Код по своему действию _задает_ или _рендерит_ `inputAddress`. Следует исходить из этого.

2021-06-28 18:44 UTC, MikhailinNik commented on js/map.js
> +  inputAddress.value = `${address.lat.toFixed(5)},${address.lng.toFixed(5)}`;
может тогда renderAddress?)

2021-06-28 19:12 UTC, AlexMasterov commented
👍🏻

2021-06-28 19:12 UTC, merged